# SOPS configuration for NixOS secrets
# Age keys derived from SSH host keys via ssh-to-age

keys:
  - &sakost-pc age1hctl9v9qq7fcp3qltmxlndhk24d60calvn962ykm4fwkw8d7j4pqushe0g

creation_rules:
  # sing-box proxy configuration (stored as binary for simplicity)
  - path_regex: secrets/sing-box\.json$
    key_groups:
      - age:
          - *sakost-pc
