# SOPS configuration for NixOS secrets
# Generate age keys with: age-keygen -o secrets/keys/sakost-pc-portable.txt
# Then add the public key here

keys:
  - &sakost-pc age1t9c3pfj4t4haq7267h9grj20lg5fcnfnsd9eavau40ptx5j9ffmsq250ex

creation_rules:
  # sing-box proxy configuration (stored as binary for simplicity)
  - path_regex: secrets/sing-box\.json$
    key_groups:
      - age:
          - *sakost-pc
