project_name: "nixos-config"

languages:
- nix
- bash

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths:
- "result"
- "result-*"
- "*.age"
- "secrets/keys/"

read_only: false

excluded_tools: []
included_optional_tools: []
fixed_tools: []

initial_prompt: |
  This is a multi-host NixOS flake configuration for user sakost.

  Structure:
  - hosts/         — per-host configs (sakost-pc, sakost-pc-portable)
  - modules/       — system NixOS modules using custom.* option pattern
  - home/          — home-manager config (programs, desktop)
  - secrets/       — SOPS-encrypted secrets (age)

  System modules follow: options.custom.<category>.<name>.enable = lib.mkEnableOption "...";
  Desktop: Hyprland + Waybar + Rofi + Alacritty, TokyoNight theme.
  Packages: GUI apps in home/programs/gui-apps.nix, CLI tools in home/sakost.nix.